# Generated by Django 2.2.5 on 2023-02-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0004_auto_20230223_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Cucumber', 'Cucumber'), ('Eggplant', 'Eggplant'), ('Lettuce', 'Lettuce'), ('Cherry Tomato', 'Cherry Tomato'), ('Tomato', 'Tomato')], max_length=60, null=True),
        ),
    ]
