# Generated by Django 2.2.5 on 2023-03-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0012_auto_20230301_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Semi-Annual', 'Semi-Annual'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cherry Tomato', 'Cherry Tomato'), ('Cucumber', 'Cucumber'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Eggplant', 'Eggplant')], max_length=60, null=True),
        ),
    ]
