# Generated by Django 2.2.5 on 2023-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0016_auto_20230302_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Semi-Annual', 'Semi-Annual')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Cherry Tomato', 'Cherry Tomato'), ('Cucumber', 'Cucumber'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Eggplant', 'Eggplant'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Lettuce', 'Lettuce')], max_length=60, null=True),
        ),
    ]
