# Generated by Django 2.2.5 on 2023-02-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Semi-Annual', 'Semi-Annual'), ('Weekly', 'Weekly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('Eggplant', 'Eggplant'), ('Cherry Tomato', 'Cherry Tomato'), ('Cucumber', 'Cucumber'), ('Lettuce', 'Lettuce')], max_length=60, null=True),
        ),
    ]
