# Generated by Django 2.2.5 on 2023-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0003_auto_20230223_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Semi-Annual', 'Semi-Annual')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Cucumber', 'Cucumber'), ('Eggplant', 'Eggplant'), ('Tomato', 'Tomato'), ('Cherry Tomato', 'Cherry Tomato')], max_length=60, null=True),
        ),
    ]
