# Generated by Django 2.2.5 on 2023-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0005_auto_20230227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='description',
            field=models.TextField(blank=True, default='ERASE this section - Enter your comments here, we will contact you about current selections and pricing shortly! Thank you! - ERASE this section', max_length=255),
        ),
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Bi-Weekly', 'Bi-Weekly'), ('Semi-Annual', 'Semi-Annual'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Cherry Tomato', 'Cherry Tomato'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cucumber', 'Cucumber'), ('Eggplant', 'Eggplant')], max_length=60, null=True),
        ),
    ]
