# Generated by Django 2.2.5 on 2023-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0007_auto_20230228_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Semi-Annual', 'Semi-Annual')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Cherry Tomato', 'Cherry Tomato'), ('Lettuce', 'Lettuce'), ('Eggplant', 'Eggplant'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cucumber', 'Cucumber'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix')], max_length=60, null=True),
        ),
    ]
