# Generated by Django 2.2.5 on 2023-03-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0009_auto_20230301_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Semi-Annual', 'Semi-Annual'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Eggplant', 'Eggplant'), ('Cherry Tomato', 'Cherry Tomato'), ('Lettuce', 'Lettuce'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Cucumber', 'Cucumber')], max_length=60, null=True),
        ),
    ]
