# Generated by Django 2.2.5 on 2023-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0013_auto_20230301_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly'), ('Semi-Annual', 'Semi-Annual')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Eggplant', 'Eggplant'), ('Cherry Tomato', 'Cherry Tomato'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cucumber', 'Cucumber'), ('Lettuce', 'Lettuce'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix')], max_length=60, null=True),
        ),
    ]
