# Generated by Django 2.2.5 on 2023-03-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0017_auto_20230302_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Semi-Annual', 'Semi-Annual'), ('Bi-Weekly', 'Bi-Weekly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Cherry Tomato', 'Cherry Tomato'), ('Lettuce', 'Lettuce'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Eggplant', 'Eggplant'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cucumber', 'Cucumber'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix')], max_length=60, null=True),
        ),
    ]
