# Generated by Django 2.2.5 on 2023-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCasualGardener', '0018_auto_20230302_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='subscription',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Semi-Annual', 'Semi-Annual'), ('Monthly', 'Monthly'), ('Bi-Weekly', 'Bi-Weekly')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='vegetable',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Leafy Vegetable Mix', 'Leafy Vegetable Mix'), ('Multi Tomato Mix', 'Multi Tomato Mix'), ('Cucumber Eggplant Squash Mix', 'Cucumber Eggplant Squash Mix'), ('Cucumber', 'Cucumber'), ('Cherry Tomato', 'Cherry Tomato'), ('Eggplant', 'Eggplant')], max_length=60, null=True),
        ),
    ]
