# Generated by Django 4.1.6 on 2023-02-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms'), ('Mrs.', 'Mrs.')], max_length=60, null=True),
        ),
    ]
