# Generated by Django 4.1.6 on 2023-02-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Ms.', 'Ms'), ('Mr.', 'Mr.')], max_length=60, null=True),
        ),
    ]
