# Generated by Django 2.1.5 on 2023-02-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20230209_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Ms.', 'Ms'), ('Mr.', 'Mr.')], max_length=60, null=True),
        ),
    ]
