# Generated by Django 2.1.5 on 2023-02-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20230210_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms'), ('Mrs.', 'Mrs.')], max_length=60, null=True),
        ),
    ]
